import Head from 'next/head';
import Mainbar from '../Components/Mainbar';
import Sidebar from '../Components/Sidebar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        {/* Sidebar */}
        <Sidebar />

        {/* Mainbar */}
        <Mainbar />
      </main>
    </div>
  )
}
